on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: arm-none-eabi-gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '10.3-2021.10'

    - name: Install Python dependencies
      run: python3 -m pip install --upgrade pip crcmod

    - name: Checkout
      uses: actions/checkout@v3

    - name: Submodules
      run: git submodule update --init --recursive --depth 1

    - name: Make
      run:  make

    - name: size
      run:  arm-none-eabi-size firmware

    - name: rename
      run: mv firmware.bin rt-890-oefw-community-${{ github.event.release.tag_name }}.bin

    - name: 'Add FW .bin to release'
      uses: svenstaro/upload-release-action@v2
      with:
        file: rt-890-oefw-community-${{ github.event.release.tag_name }}.bin
